version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - flask
    environment:
      VIRTUAL_HOST: example.com
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: example.com

  flask:
    container_name: flask
    command: "gunicorn app:app --bind 0.0.0.0:8000 --reload"
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:8000"
    volumes:
      - ./src:/app
